apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-toolkit-minio
  namespace: minio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-toolkit-minio
  namespace: minio
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-toolkit-minio
  namespace: minio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-toolkit-minio
subjects:
  - kind: ServiceAccount
    name: k8s-toolkit-minio
    namespace: minio
# ---
# Add wait for minio buckets to be created
