apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-toolkit-eso
  namespace: external-secrets-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-toolkit-eso
  namespace: external-secrets-operator
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-toolkit-eso
  namespace: external-secrets-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-toolkit-eso
subjects:
  - kind: ServiceAccount
    name: k8s-toolkit-eso
    namespace: external-secrets-operator
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: wait-external-secrets-cert-controller
  namespace: external-secrets-operator
spec:
  template:
    spec:
      containers:
      - name: wait
        image: public.ecr.aws/bitnami/kubectl:1.24
        command:
        - /bin/sh
        - -c
        - |
          while ! kubectl get deploy -l app.kubernetes.io/name=external-secrets-cert-controller --namespace external-secrets-operator; do echo "waiting for external secrets cert controller to be valid, sleeping 5 seconds"; sleep 5; done
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit-eso
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: wait-external-secrets
  namespace: external-secrets-operator
spec:
  template:
    spec:
      containers:
      - name: wait
        image: public.ecr.aws/bitnami/kubectl:1.24
        command:
        - /bin/sh
        - -c
        - |
          while ! kubectl get deploy -l app.kubernetes.io/name=external-secrets --namespace external-secrets-operator; do echo "waiting for external secrets to be valid, sleeping 5 seconds"; sleep 5; done
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit-eso
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: wait-external-secrets-webhook
  namespace: external-secrets-operator
spec:
  template:
    spec:
      containers:
      - name: wait
        image: public.ecr.aws/bitnami/kubectl:1.24
        command:
        - /bin/sh
        - -c
        - |
          while ! kubectl get deploy -l app.kubernetes.io/name=external-secrets-webhook --namespace external-secrets-operator; do echo "waiting for external secrets webhook to be valid, sleeping 5 seconds"; sleep 5; done
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit-eso
