apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-kv-secret
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  provider:
    vault:
      server: 'http://vault.vault.svc:8200'
      # Path is the mount path of the Vault KV backend endpoint
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
# kubectl create secret generic vault-token --from-literal=token=$VAULT_TOKEN -namespace=external-secrets-operator