apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: marktalston@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cnameStrategy: Follow
        route53:
          region: us-east-1
          hostedZoneID: Z03797052EOT9S3MIV49U
          accessKeyIDSecretRef:
            name: route53-secret
            key: accesskeyid
          secretAccessKeySecretRef:
            name: route53-secret
            key: secretaccesskey
      selector:
        dnsZones:
        - kubelab.app
