apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  virtualhost:
    fqdn: minio.kubelab.app
  routes:
  - conditions:
    - prefix: /
    services:
    - name: minio
      port: 9000
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio-console
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  virtualhost:
    fqdn: minio-console.kubelab.app
  routes:
  - conditions:
    - prefix: /
    services:
    - name: minio-console
      port: 9001
