apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: route53-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  target:
    name: route53-secret
  data:
  - remoteRef:
      key: route53
      property: accesskeyid
    secretKey: accesskeyid
  - remoteRef:
      key: route53
      property: secretaccesskey
    secretKey: secretaccesskey
