apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: route53-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  target:
    name: route53-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
  - extract:
      key: /route53
