apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secret-store-mgmt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  project: default
  source:
    repoURL: https://github.com/malston/platform-gitops.git
    path: registry/mgmt/components/cluster-secret-store
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
