apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://github.com/malston/platform-gitops.git
    path: registry/mgmt/components/contour
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tanzu-system-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
