apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-mgmt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://github.com/malston/platform-gitops.git
    path: registry/mgmt/components/minio
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
