kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: '0'
subjects:
  - kind: ServiceAccount
    name: argocd
    namespace: argocd
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: '0'
subjects:
  - kind: ServiceAccount
    name: argo-server
    namespace: argo
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    tkg.tanzu.vmware.com/tanzu-package: contour-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: contour-packages-sa
  namespace: packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    tkg.tanzu.vmware.com/tanzu-package: contour-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: contour-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    tkg.tanzu.vmware.com/tanzu-package: contour-packages
    kapp.k14s.io/update-strategy: "fallback-on-replace"
  name: contour-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: contour-packages-sa
  namespace: packages
