apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vault
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  virtualhost:
    fqdn: vault.homelab.io
    tls:
      secretName: vault-tls
  routes:
    - conditions:
      - prefix: /
      services:
        - name: vault
          port: 80