apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: vault
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  virtualhost:
    fqdn: vault.kubelab.app
    tls:
      secretName: cert-manager/prod-wildcard-certs
  routes:
  - conditions:
    - prefix: /
    services:
    - name: vault
      port: 8200
